- Cargo.toml
- docs/snpguest.1.adoc
- src/display.rs
- src/hyperv/mod.rs
- src/main.rs
- src/report.rs
- src/verify.rs
This PR introduces two new features:
1. Detecting if snpguest is running inside of a Azure CVM
2. If so, fetching the attestation report from the vTPM, rather than the /dev/sev-guest device
> Azure detection + attestation report fetch

- Cargo.toml
- src/main.rs
- src/report.rs
Adding a feature flag to block out HyperV
specific code blocks, imports, etc.
> hyperv: Adding feature flag for hyperv

- src/report.rs
Fixing the way the attestation report is being written into a file using serialization.
Fixes bug in issue https://github.com/virtee/snpguest/issues/25
> Fixing report request serialization

- Cargo.lock
- src/certs.rs
- src/fetch.rs
Previously to this fix #37 , URL requests would write the contents of "404 Not Found" to the certificate being requested. This adds a simple check to make sure the certificate was successfully pulled before writing it.
> Fetch: Adding status check to HTTP response

- src/main.rs
When attempting to build with the hyperv flag, previously the hv variable passed to report::get_report was a function pointer and not a boolean value. Changing the non-hyperv state to call the function which returns a boolean makes this work correctly
> hyperv: Missing closure for boolean state.

- Cargo.lock
- Cargo.toml
- src/certs.rs
- src/fetch.rs
- src/verify.rs
With the release of the VLEK, there is a separate api endpoint for requesting VLEK signing keys which are known as an AMD Signing VLEK Key (ASVK). This adds logic to handle these special use-cases. As the [GHCB](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56421.pdf#page=53) does not offer a unique GUID, assumptive logic must be applied to when the file should be named appropriately ASVK or ASK.
> VLEK: Adding ASVK Support

- src/verify.rs
use 'attestation' instead of 'attesation'
> Fix typo in verify_attestation() function

- Cargo.lock
- Cargo.toml
- src/fetch.rs
There is a bug in the code as the AMD KDS is URL case-sensitive.
> URL: Fixing URL breakage

- src/report.rs
As below, SEV-SNP guest firmware device file is usually /dev/sev-guest at present. thus it'd be better if the context message contained it.
https://github.com/virtee/sev/blob/v3.1.1/src/firmware/guest/mod.rs#L66
> Fix the context message for failing to open SEV firmware.

- src/main.rs
Remove `subcommand` trait from `Ok`. This fixes the prior behaviour where the usage was printed rather than the expected functionality occurring.
With the fix:
```
$ sudo snpguest ok 
[ PASS ] - SEV: ENABLED
[ PASS ] - SEV-ES: ENABLED
[ PASS ] - SNP: ENABLED
[ PASS ] - Optional Features statuses:
[ PASS ]   - VTOM: DISABLED
[ PASS ]   - ReflectVC: DISABLED
[ PASS ]   - Restricted Injection: DISABLED
[ PASS ]   - Alternate Injection: DISABLED
[ PASS ]   - Debug Swap: DISABLED
[ PASS ]   - Prevent Host IBS: DISABLED
[ PASS ]   - SNP BTB Isolation: DISABLED
[ PASS ]   - VMPL SSS: DISABLED
[ PASS ]   - Secure TSE: DISABLED
[ PASS ]   - VMG Exit Parameter: DISABLED
[ PASS ]   - IBS Virtualization: DISABLED
[ PASS ]   - VMSA Reg Prot: DISABLED
[ PASS ]   - SMT Protection: DISABLED
```
Fixes #55
> fix: remove subcommand trait on `ok` command

- Cargo.lock
With the latest stable branch, some of the libraries are broken. Updating them fixes the issue we were facing.
> rust: Patching for latest rust update

- Cargo.lock
- Cargo.toml
- docs/snpguest.1.adoc
- src/main.rs
- src/preattestation.rs
Added functionality to generate different pre-attestation components
- Generate a guest launch digest (measurement)
- Generate an ID-BLOCK and AUTH-BLOCK
- Generate an OVMF-hash
- Generate key-digests for openssl keys
> Adding preattestation functionality to snpguest

- README.md
snpguest is included as part of the official repositories for openSUSE Leap, Tumbleweed and SUSE Linux Enterprise Servers but, If users want to build the latest and greatest Git version, they must enable the "devel_basis" pattern.
> Added build dependencies for openSUSE

- README.md
It seems that the current snpguest tool will fail to execute as expected without the option <endorser> when requesting the certificate authority chain (ARK & ASK) from the KDS.
> Update the README.md: fix the uncomplete description of the fetch ca command

- .github/workflows/lint.yml
- Cargo.lock
- Cargo.toml
Addresses https://github.com/virtee/snpguest/issues/68. I think it should be fine to remove this strict semvar, but happy to make any changes you folks see fit!
> Remove strict versioning on clap dependency

- .github/workflows/lint.yml
- Cargo.lock
- Cargo.toml
Following our conversation in https://github.com/virtee/snpguest/pull/69#issuecomment-2332403871, upgrade the toolchain to 1.80 to keep up with the latest distro MSRV releases
It built for me here:
```
$ cargo build
warning: `/home/kevinhui/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/home/kevinhui/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
Compiling quote v1.0.37
Compiling libc v0.2.158
Compiling shlex v1.3.0
Compiling serde v1.0.209
Compiling unicode-xid v0.2.5
Compiling tower-service v0.3.3
Compiling indexmap v2.5.0
Compiling cc v1.1.16
Compiling syn v2.0.77
Compiling …
```
> Upgrade MSRV to 1.80

- .github/workflows/lint.yml
- src/certs.rs
- src/fetch.rs
- src/key.rs
- src/preattestation.rs
Clap does not use FromStr, it handles inputs separately. Need to add `ignore_case` to make inputs case insensitive.
> Fixing case sensitivity bug

- Cargo.lock
- src/fetch.rs
- src/verify.rs
Adding Turin support for certificate fetching.
A recent update to the CA certificates changed the name of the ASK common name to SEV-<processor name>, we added that option to our parser so that certificate verification still works.
> Adding Turin support and updating ASK CN

- Cargo.lock
- Cargo.toml
- src/fetch.rs
Adding the new from_pem_bytes function to the fetch function for the CA in order to solve the issue of different sized certificates for Turin.
I wanted to completely remove the openssl dependency on this PR, but I'm waiting on https://github.com/virtee/sev/pull/266
We could merge this now and then on the next release remove that dependency
> Fix certificate fetch bug for Turin

- .github/workflows/create_release.yml
We would like to automate the creation of musl binaries for the application when new tags are released.
> CI: Fixing create_release workflow

- Cargo.lock
- Cargo.toml
- docs/snpguest.1.adoc
- src/fetch.rs
- src/report.rs
- src/verify.rs
This update bumps the dependency to version 6 of the SEV libarary.
Besides fixing the code compatibility, we changed the way certificate fetching is done.
Now the user is expected to provide a V3 attestation report, with chich we can tell for what processor model we will be getting the certificates from. If the user doesn't have a V3 report in the firmware, or wants to get certs for a different proc model, they can still use the --processor_model flag.
The verification also add a --processor_model flag in case they need to attest a V2 of the report.
> Updating to version 6 of library and fixing attestation

- src/preattestation.rs
Had initrd and append as required when using a kernel for measurement. There are use-cases where the just the kernel is used (uki images), so we remove the initrd and append as required when using kernel. Kernel is still needed if user is passing either the initrd or the append.
> Removing intird and append requirement for kernel measurements

- Cargo.lock
- Cargo.toml
Bumping crate version to 0.9.0 in order to cut release.
> Update version (0.9.0)

- Cargo.lock
- Cargo.toml
Some report bug fixes needed were just released on the 6.1.0 library, so we are doing a fix release for snpguest to include these.
> Updating SEV library to 6.1.0 and updating version to 0.9.1

- Cargo.lock
- Cargo.toml
Fixes #98 virtee/sev 6.2.1 fixes incorrect serialization of TCB_VERSION on pre-Turin CPUs (Milan/Genoa). – Attestation reports were rewritten into Turin format, causing invalid TCB versions and signature-verification failures. Release notes: https://github.com/virtee/sev/releases/tag/v6.2.1
fixup: bump virtee/sev in Cargo.toml as well
> deps: bump virtee/sev to 6.2.1 (fix TCB-serialization bug)

- src/verify.rs
This PR removes the `mismatched_lifetime_syntaxes` warning that appears on every build:
```plaintext
warning: hiding a lifetime that's elided elsewhere is confusing
--> src/verify.rs:170:16
|
170 |         fn oid(&self) -> Oid {
|                ^^^^^     --- the same lifetime is hidden here
|                |
|                the lifetime is elided here
|
= help: the same lifetime is referred to in inconsistent ways, making the signature confusing
= note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: use `'_` for type paths
|
170 |         fn oid(&self) -> Oid<'_> {
|                             ++++
```
The warning stems from returning `Oid` without an explicit lifetime while the same lifetime is written explicitly on `&self`. Adding a `’static` lifetime resolves the …
> fix(verify): make `SnpOid::oid` return `Oid<'static>` to silence lifetime warning

- README.md
- src/fetch.rs
This PR introduces a new subcommand:
```bash
snpguest fetch crl
```
The command fetches **Certificate Revocation Lists (CRLs)** directly from the AMD Key Distribution Service (KDS). With this change, `snpguest` can now retrieve all attestation collateral (AMD CA certs, VEKs, and CRLs).
```bash
snpguest fetch crl $ENCODING $CERTS_DIR $PROCESSOR_MODEL --endorser $ENDORSER
snpguest fetch crl $ENCODING $CERTS_DIR --report $ATT_REPORT_PATH --endorser $ENDORSER
```
See the updated `README.md` for more details.
- VM: Google Cloud N2D `n2d-highmem-4`
- Processor: AMD EPYC 7B13 (Milan)
- OS image: `ubuntu-accelerator-2404-amd64-with-nvidia-570-v20250819`
- Kernel: `6.14.0-1016-gcp`
```bash
mkdir workspace
cd workspace
snpguest fetch crl der . milan -e vcek # => crl.der
sleep 10 # avoid rate-limits …
```
> feat(fetch): add `fetch crl` subcommand

- src/main.rs
This PR removes an unnecessary import of `clap::arg` in `main.rs`. Attribute macros `#[arg(...)]` do not require `use clap::arg`, which may cause error when testing with newer toolchain e.g. `1.92.0-nightly (595b9a498 2025-10-03)`:
```console
Error:   --> src/main.rs:25:12
|
25 | use clap::{arg, Parser, Subcommand, ValueEnum};
|            ^^^
|
= note: `-D unused-imports` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_imports)]`
```
Removing this keeps CI green across all toolchains (stable, beta, nightly and MSRV 1.86.0)
> chore(main): remove unnecessary import `clap::arg`

- README.md
- src/clparser/mod.rs
- src/key.rs
- src/main.rs
This PR introduces a custom integer parser able to accept decimal, prefixed hexadecimal (`0x…`) and prefixed binary (`0b…`) strings in the `snpguest` CLI, and wires it into the `key` subcommand.
This was discussed and proposed in PR #115.
* Add `src/clparser/mod.rs` implementing the multi-format integer parser `parse_int_auto_radix::<T>`
* Enable multi-format CLI arguments in the `key` subcommand ― arguments `gfs`, `gsvn`, `tcbv` and `lmv` now use `clparser::parse_int_auto_radix` as their `value_parser`
* Refactor `KeyArgs` to use typed defaults and streamline validation logic
* Update `README.md` to document the new multi-format parsing in CLI examples
- VM: GCE n2d-standard-2 (AMD Milan)
- OS image: ubuntu-2404-noble-amd64-v20250805
- Linux kernel: 6.14.0-1014-gcp
All affected CLI …
> feat: Support multi-format integer parsing for CLI arguments
